### PR TITLE
Made a better disable-rendering-button

### PR DESCRIPTION
**Pull request by JensKanstrupLarsen**

### CODE REVIEW

**Comment by dybber** [comment]
Updated to be able to merge.

**Comment by dybber** [comment]
Not sure why the #77 PR's commit ended up in here, but still seems it should be able to merge.

I have some suggestions:
 - I think it would be nice if the state of the SimulationArea is just frozen, when you push the Disable Rendering Button
 - The button is not very aesthetically pleasing. It doesn't really look like an eye, I'm sorry, it looks like a weird kind of small slider-thing inside a huge square. The grey square is also big an clunky, and obscures a large part of the drawing area. 
 - Right now I'm not sure this is actually a good idea, an alternative could be a right-click menu on the Simulation area

**Comment by JensKanstrupLarsen** [comment]
- I agree that it makes more sense for it to just freeze. I'll try to change it to how it is now.
- Well, I never prided myself in my artistic skills. And you are probably right in that it is too visually obscuring.
- Are right click menus available through PyQt? Otherwise, maybe we should just do the toggling by right clicking the simulation area.

**Comment by dybber** [comment]
I think it should be pretty easy to do a right click menu, let me just check and see if I can get it to work.

**Comment by dybber** [comment]
I've made it use a context-menu instead, looks like this on Mac:
Screenshot 2020-09-21 at 15 31 49

**Pull request merged**
